channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pytorch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.64.0
  - mlflow==1.26.0
  - pip==21.2.4
  - pip:
      - azure-ai-ml==1.2.0
      - azureml-mlflow==1.48.0
      - 'monai[nibabel, ignite, tqdm]'
      - numpy
      - tensorboard
      - scikit-learn
      - matplotlib